version: 2

models:
  - name: dim_security
    columns:
      - name: security_id
        tests:
          - unique
          - not_null
      - name: ticker
        tests:
          - not_null
      - name: row_hash
        tests:
          - not_null

  - name: dim_shareholder
    columns:
      - name: shareholder_id
        tests:
          - unique
          - not_null

  - name: fact_shareholder_holding
    columns:
      - name: holding_id
        tests:
          - unique
          - not_null
      - name: security_id
        tests:
          - not_null
