import React, { useEffect, useRef, useState } from "react";
import type { KeyboardEvent } from "react";

import { api, dagsterBaseUrl } from "../../api";
import type { ReviewRow, RowsetRow } from "./types";
import { formatCellValue, cellKey, buildIssueCellMap, startOfMonth, addMonths, mondayWeekdayIndex, monthLabel, toIsoDate } from "./utils";
import { WEEKDAY_LABELS } from "./constants";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type EditingCell = { rowId: number; column: string; table: string } | null;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatValue(value: unknown, column?: string): string {
  return formatCellValue(value, column);
}

function shortRunId(runId: string): string {
  return runId.length > 8 ? runId.slice(0, 8) + "\u2026" : runId;
}

function sortByFiler(rows: RowsetRow[]): RowsetRow[] {
  return [...rows].sort((a, b) => String(a.filer_name ?? "").localeCompare(String(b.filer_name ?? "")));
}

const dimUpperStyle: React.CSSProperties = {
  color: "var(--text-dim)",
  fontSize: "0.74rem",
  textTransform: "uppercase",
};

// ---- DAG flowchart --------------------------------------------------------

type DagNode = { id: string; label: string; stepKey: string; stepKeys?: string[]; col: number; row: number; assetKeys?: string[]; groupName?: string; groups?: string[]; metadata?: Record<string, unknown> };
type DagEdge = [string, string];

// Generated by ops/scripts/generate_dag_topology.py — true to Dagster definitions
import dagTopology from "../../generated/dag_topology.json";

const _wf = (dagTopology as unknown as Record<string, { nodes: DagNode[]; edges: DagEdge[] }>)["security_shareholder"];
const DAG_NODES: DagNode[] = _wf.nodes;
const DAG_EDGES: DagEdge[] = _wf.edges;

// Identify export nodes: any node that comes after the review stage.
// We detect them as nodes whose group is validated_export, OR nodes
// that are only reachable from validated_export nodes.
const EXPORT_GROUP_NAMES = new Set(["validated_export"]);
const _exportDirect = new Set(DAG_NODES.filter((n) => EXPORT_GROUP_NAMES.has(n.groupName ?? "")).map((n) => n.id));
const EXPORT_NODE_IDS = new Set(_exportDirect);
// Also include nodes only fed by export nodes (e.g., csv_export)
for (const edge of DAG_EDGES) {
  if (_exportDirect.has(edge[0])) EXPORT_NODE_IDS.add(edge[1]);
}

function computeNodeStatuses(
  steps: Array<Record<string, unknown>>,
  pipelineStatus: string,
  capturing?: boolean,
  captureComplete?: boolean,
  sourcesReady?: boolean,
  approvalState?: string,
): Record<string, string> {
  const result: Record<string, string> = {};
  const isExported = pipelineStatus === "exported" || approvalState === "exported";
  const isApproved = approvalState === "approved";
  const isFinished = ["pending_review", "exported", "historical_loaded"].includes(pipelineStatus);
  const isRunning = pipelineStatus === "running" || pipelineStatus === "queued";

  const stepMap = new Map<string, string>();
  for (const s of steps) stepMap.set(String(s.step_key ?? ""), String(s.status ?? ""));

  const CAPTURE_GROUPS = new Set(["source_capture"]);
  const isCapture = (node: DagNode) => CAPTURE_GROUPS.has(node.groupName ?? "");

  const sortedNodes = [...DAG_NODES].sort((a, b) => a.col - b.col);
  for (const node of sortedNodes) {
    const allKeys = node.stepKeys ?? [node.stepKey];
    const matchedStatuses = allKeys.map((k) => stepMap.get(k)).filter(Boolean) as string[];
    const stepStatus = matchedStatuses.length > 0
      ? (matchedStatuses.includes("failed") ? "failed"
        : matchedStatuses.includes("running") ? "running"
        : matchedStatuses.every((s) => s === "succeeded") ? "succeeded"
        : matchedStatuses.includes("succeeded") ? "running"
        : matchedStatuses[0])
      : undefined;

    // ── Capture nodes: driven by UI capture state + step data ──
    if (isCapture(node)) {
      if (capturing) { result[node.id] = "running"; continue; }
      if (stepStatus === "succeeded" || stepStatus === "running" || stepStatus === "failed") {
        result[node.id] = stepStatus; continue;
      }
      if (captureComplete || sourcesReady || isFinished || isApproved || isExported || isRunning) {
        result[node.id] = "succeeded"; continue;
      }
      result[node.id] = "idle"; continue;
    }

    // ── Export nodes: driven purely by approval state ──
    if (EXPORT_NODE_IDS.has(node.id)) {
      if (isExported) { result[node.id] = "succeeded"; continue; }
      if (isApproved) { result[node.id] = "running"; continue; }
      result[node.id] = "idle"; continue;
    }

    // ���─ Middle nodes (transform, review): use step data directly ──
    if (isFinished || isApproved || isExported) {
      result[node.id] = "succeeded"; continue;
    }

    if (stepStatus === "succeeded") { result[node.id] = "succeeded"; continue; }
    if (stepStatus === "running") { result[node.id] = "running"; continue; }
    if (stepStatus === "failed") { result[node.id] = "failed"; continue; }

    // No step data — check if all upstream nodes succeeded
    if (isRunning) {
      const upstreamDone = DAG_EDGES
        .filter(([, to]) => to === node.id)
        .every(([from]) => result[from] === "succeeded");
      result[node.id] = upstreamDone ? "running" : "idle";
      continue;
    }

    result[node.id] = "idle";
  }

  return result;
}

function PipelineDag({ steps, pipelineStatus, capturing, captureComplete, sourcesReady, approvalState }: { steps: Array<Record<string, unknown>>; pipelineStatus: string; capturing?: boolean; captureComplete?: boolean; sourcesReady?: boolean; approvalState?: string }) {
  const [hoveredNode, setHoveredNode] = useState<string | null>(null);
  const hideTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const wrapRef = useRef<HTMLDivElement>(null);
  const tooltipRef = useRef<HTMLDivElement>(null);

  function showNode(id: string) {
    if (hideTimer.current) { clearTimeout(hideTimer.current); hideTimer.current = null; }
    setHoveredNode(id);
  }
  function scheduleHide() {
    if (hideTimer.current) clearTimeout(hideTimer.current);
    hideTimer.current = setTimeout(() => setHoveredNode(null), 150);
  }
  function cancelHide() {
    if (hideTimer.current) { clearTimeout(hideTimer.current); hideTimer.current = null; }
  }

  const nodeW = 72, nodeH = 36, gapX = 32, gapY = 6, padX = 8, padY = 8;
  const maxCol = Math.max(...DAG_NODES.map((n) => n.col));
  const maxRow = Math.max(...DAG_NODES.map((n) => n.row));
  const svgW = padX * 2 + (maxCol + 1) * nodeW + maxCol * gapX;
  const svgH = padY * 2 + (maxRow + 1) * (nodeH + gapY);

  function nx(col: number) { return padX + col * (nodeW + gapX); }
  function ny(row: number) { return padY + row * (nodeH + gapY); }
  function cy(node: DagNode) { return ny(node.row) + nodeH / 2; }

  const statusColor: Record<string, string> = {
    idle: "var(--border-subtle)",
    pending: "var(--text-dim)",
    running: "var(--accent-blue)",
    succeeded: "var(--accent-green)",
    failed: "var(--accent-red)",
  };

  const statusBg: Record<string, string> = {
    idle: "transparent",
    pending: "rgba(90,95,106,0.08)",
    running: "rgba(79,143,247,0.12)",
    succeeded: "rgba(62,207,122,0.10)",
    failed: "rgba(239,107,107,0.12)",
  };

  const statusLabel: Record<string, string> = {
    idle: "Idle", pending: "Pending", running: "Running", succeeded: "Succeeded", failed: "Failed",
  };

  const statuses = computeNodeStatuses(steps, pipelineStatus, capturing, captureComplete, sourcesReady, approvalState);

  const stepByKey = new Map<string, Record<string, unknown>>();
  for (const s of steps) stepByKey.set(String(s.step_key ?? ""), s);

  const hoveredDagNode = hoveredNode ? DAG_NODES.find((n) => n.id === hoveredNode) : null;
  const hoveredSteps = hoveredDagNode
    ? (hoveredDagNode.stepKeys ?? [hoveredDagNode.stepKey]).map((k) => stepByKey.get(k)).filter(Boolean)
    : [];
  const hoveredStep = hoveredSteps.length > 0 ? hoveredSteps[0] : null;
  const hoveredStatus = hoveredDagNode ? (statuses[hoveredDagNode.id] ?? "idle") : "idle";

  type TipRow = { label: string; value: string; mono?: boolean; href?: string };
  type TipSection = { title: string; rows: TipRow[] };

  function fmtKey(k: string): string {
    return k.replace(/^dagflow_/, "").replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  }

  function tooltipSections(): TipSection[] {
    if (!hoveredDagNode) return [];
    const sections: TipSection[] = [];

    // 1. Identity
    const identity: TipRow[] = [
      { label: "Op", value: hoveredDagNode.stepKey, mono: true },
    ];
    if (hoveredDagNode.groupName) identity.push({ label: "Group", value: hoveredDagNode.groupName });
    if (hoveredDagNode.assetKeys && hoveredDagNode.assetKeys.length > 0) {
      for (const ak of hoveredDagNode.assetKeys) {
        identity.push({ label: "Asset", value: ak, mono: true, href: `${dagsterBaseUrl}/assets/${encodeURIComponent(ak)}` });
      }
    }
    sections.push({ title: "Dagster", rows: identity });

    // 2. Asset metadata from definitions
    const nodeMeta = hoveredDagNode.metadata;
    if (nodeMeta && typeof nodeMeta === "object") {
      const metaRows: TipRow[] = [];
      for (const [k, v] of Object.entries(nodeMeta)) {
        if (v === null || v === undefined || v === "") continue;
        metaRows.push({ label: fmtKey(k), value: typeof v === "object" ? JSON.stringify(v) : String(v) });
      }
      if (metaRows.length > 0) sections.push({ title: "Metadata", rows: metaRows });
    }

    // 3. Runtime sub-steps
    for (const step of hoveredSteps) {
      if (!step) continue;
      const stepLabel = String(step.step_label ?? step.step_key ?? "Step");
      const stepRows: TipRow[] = [];
      if (step.started_at) stepRows.push({ label: "Started", value: new Date(String(step.started_at)).toLocaleString() });
      if (step.ended_at) stepRows.push({ label: "Ended", value: new Date(String(step.ended_at)).toLocaleString() });
      if (step.started_at && step.ended_at) {
        const ms = new Date(String(step.ended_at)).getTime() - new Date(String(step.started_at)).getTime();
        stepRows.push({ label: "Duration", value: ms < 1000 ? `${ms}ms` : `${(ms / 1000).toFixed(1)}s` });
      }
      const meta = step.metadata as Record<string, unknown> | undefined;
      if (meta && typeof meta === "object") {
        const skip = new Set(["stage"]);
        for (const [k, v] of Object.entries(meta)) {
          if (skip.has(k) || v === null || v === undefined || v === "") continue;
          const val = typeof v === "object" ? JSON.stringify(v) : String(v);
          const isPath = k.includes("path") || k.includes("key") || k.includes("checksum") || k.includes("file_id") || k.includes("url");
          const href = undefined;
          stepRows.push({ label: fmtKey(k), value: val, mono: isPath, href });
        }
      }
      if (stepRows.length > 0) sections.push({ title: stepLabel, rows: stepRows });
    }

    return sections;
  }

  // Viewport-aware tooltip positioning
  useEffect(() => {
    if (!tooltipRef.current || !wrapRef.current) return;
    const tip = tooltipRef.current;
    const wrap = wrapRef.current;
    const wrapRect = wrap.getBoundingClientRect();
    const tipRect = tip.getBoundingClientRect();

    // Clamp right edge
    if (tipRect.right > window.innerWidth - 8) {
      const overflow = tipRect.right - window.innerWidth + 12;
      tip.style.transform = `translateX(-${overflow}px)`;
    } else {
      tip.style.transform = "";
    }
    // Clamp bottom edge
    if (tipRect.bottom > window.innerHeight - 8) {
      const overflow = tipRect.bottom - window.innerHeight + 12;
      tip.style.marginTop = `-${overflow}px`;
    } else {
      tip.style.marginTop = "";
    }
  }, [hoveredNode]);

  const tipX = hoveredDagNode ? nx(hoveredDagNode.col) + nodeW + 8 : 0;
  const tipY = hoveredDagNode ? ny(hoveredDagNode.row) : 0;

  return (
    <div ref={wrapRef} style={{ position: "relative", display: "inline-block" }}>
      <svg width={svgW} height={svgH} style={{ display: "block" }}>
        {DAG_EDGES.map(([from, to]) => {
          const fromNode = DAG_NODES.find((n) => n.id === from)!;
          const toNode = DAG_NODES.find((n) => n.id === to)!;
          const x1 = nx(fromNode.col) + nodeW;
          const y1 = cy(fromNode);
          const x2 = nx(toNode.col);
          const y2 = cy(toNode);
          const edgeStatus = statuses[fromNode.id] ?? "idle";
          const color = statusColor[edgeStatus] ?? statusColor.idle;
          return (
            <path key={`${from}-${to}`}
              d={`M${x1},${y1} C${x1 + gapX / 2},${y1} ${x2 - gapX / 2},${y2} ${x2},${y2}`}
              fill="none" stroke={color} strokeWidth={1.5} />
          );
        })}
        {DAG_NODES.map((node) => {
          const x = nx(node.col);
          const y = ny(node.row);
          const status = statuses[node.id] ?? "idle";
          const color = statusColor[status] ?? statusColor.idle;
          const bg = statusBg[status] ?? "transparent";
          const lines = node.label.split("\n");
          return (
            <g key={node.id} style={{ cursor: "pointer" }}
              onMouseEnter={() => showNode(node.id)}
              onMouseLeave={scheduleHide}>
              <rect x={x} y={y} width={nodeW} height={nodeH} rx={5} ry={5}
                fill={bg} stroke={color} strokeWidth={status === "running" ? 2 : 1.5}>
                {status === "running" && (
                  <animate attributeName="opacity" values="1;0.35;1" dur="1.8s" repeatCount="indefinite" />
                )}
              </rect>
              <circle cx={x + 9} cy={y + nodeH / 2} r={3} fill={color}>
                {status === "running" && (
                  <animate attributeName="opacity" values="1;0.35;1" dur="1.8s" repeatCount="indefinite" />
                )}
              </circle>
              {lines.map((line, i) => (
                <text key={i} x={x + 17} y={y + nodeH / 2 + (i - (lines.length - 1) / 2) * 10}
                  fill="var(--text-secondary)" fontSize="8" fontFamily="Inter, sans-serif"
                  dominantBaseline="central" style={{ pointerEvents: "none" }}>
                  {line}
                </text>
              ))}
            </g>
          );
        })}
      </svg>

      {hoveredDagNode && (
        <div
          ref={tooltipRef}
          className="dag-tooltip"
          onMouseEnter={cancelHide}
          onMouseLeave={scheduleHide}
          style={{
            position: "absolute",
            top: tipY,
            left: tipX,
            zIndex: 50,
          }}
        >
          <div className="dag-tooltip__header">
            <span className="dag-tooltip__dot" style={{ background: statusColor[hoveredStatus] }} />
            <span className="dag-tooltip__title">{hoveredDagNode.label.replace("\n", " ")}</span>
            <span className="dag-tooltip__status" style={{ color: statusColor[hoveredStatus] }}>
              {statusLabel[hoveredStatus] ?? hoveredStatus}
            </span>
          </div>
          {tooltipSections().map((section) => (
            <div key={section.title} className="dag-tooltip__section">
              <div className="dag-tooltip__section-title">{section.title}</div>
              <dl className="dag-tooltip__meta">
                {section.rows.map(({ label, value, mono, href }, i) => (
                  <React.Fragment key={`${label}-${i}`}>
                    <dt>{label}</dt>
                    <dd className={mono ? "mono" : ""}>
                      {href ? <a href={href} target="_blank" rel="noopener noreferrer">{value}</a> : value}
                    </dd>
                  </React.Fragment>
                ))}
              </dl>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function ReviewWorkbench() {
  // ---- state ---------------------------------------------------------------
  const [businessDate, setBusinessDate] = useState<string>("");
  const [runId, setRunId] = useState<string>("");
  const [rows, setRows] = useState<ReviewRow[]>([]);
  const [expandedRowId, setExpandedRowId] = useState<number | null>(null);
  const [holdingsRows, setHoldingsRows] = useState<RowsetRow[]>([]);
  const [loadingHoldings, setLoadingHoldings] = useState(false);
  const [editingCell, setEditingCell] = useState<EditingCell>(null);
  const [editValue, setEditValue] = useState("");
  const [issuesByCell, setIssuesByCell] = useState<Record<string, true>>({});
  const [availableDates, setAvailableDates] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [committing, setCommitting] = useState(false);
  const [approving, setApproving] = useState(false);
  const [snapshotOptions, setSnapshotOptions] = useState<Array<Record<string, unknown>>>([]);
  const [approvalState, setApprovalState] = useState<string>("pending_review");
  const [pendingEdits, setPendingEdits] = useState<Record<string, string>>({});
  const [recalcedCells, setRecalcedCells] = useState<Record<string, true>>({});
  const [editedSecurityRows, setEditedSecurityRows] = useState<Set<number>>(new Set());
  const [issueRows, setIssueRows] = useState<RowsetRow[]>([]);
  const [issuesPanelOpen, setIssuesPanelOpen] = useState(true);
  const [launching, setLaunching] = useState(false);
  const [pipelineRuns, setPipelineRuns] = useState<Array<Record<string, unknown>>>([]);
  const [pipelineOpen, setPipelineOpen] = useState(false);
  const [availableDateSet, setAvailableDateSet] = useState<Set<string>>(new Set());
  const [businessDaySet, setBusinessDaySet] = useState<Set<string>>(new Set());
  const [holidayMap, setHolidayMap] = useState<Record<string, string>>({});
  const [calendarMonth, setCalendarMonth] = useState<Date>(() => startOfMonth(new Date()));
  const [capturing, setCapturing] = useState(false);
  const [captureComplete, setCaptureComplete] = useState(false);
  const [deletingSources, setDeletingSources] = useState(false);
  const [runStartedAt, setRunStartedAt] = useState<string>("");

  const editInputRef = useRef<HTMLInputElement>(null);
  const tableWrapRef = useRef<HTMLDivElement>(null);

  // ---- bootstrap -----------------------------------------------------------
  useEffect(() => {
    void bootstrap();
  }, []);

  async function bootstrap() {
    try {
      const [dates, snapshots, calDays] = await Promise.all([
        api.getAvailableSourceDates("security_master"),
        api.getReviewSnapshots("security_master"),
        api.getCalendarDays("us_sec"),
      ]);

      const bdays = new Set(calDays.filter((d) => d.is_business_day).map((d) => d.date));
      setBusinessDaySet(bdays);
      const hmap: Record<string, string> = {};
      for (const d of calDays) { if (d.holiday_name) hmap[d.date] = d.holiday_name; }
      setHolidayMap(hmap);

      const dateStrings = dates.map((d) => String(d.business_date ?? d)).sort();
      const readyDates = new Set(dates.filter((d) => d.is_ready).map((d) => String(d.business_date)));
      setAvailableDates(dateStrings);
      setAvailableDateSet(readyDates);
      setSnapshotOptions(snapshots as unknown as Array<Record<string, unknown>>);

      // pick defaults: prefer the current snapshot, then most recent
      const currentSnapshot = snapshots.find((s) => s.is_current) ?? snapshots[0] ?? null;
      if (currentSnapshot) {
        const date = String(currentSnapshot.business_date ?? "");
        const rid = String(currentSnapshot.run_id ?? "");
        setBusinessDate(date);
        setRunId(rid);
        await loadRows(date, rid);
      } else if (dateStrings.length > 0) {
        setBusinessDate(dateStrings[0]);
      }
    } catch (err) {
      setError(String((err as Error).message ?? err));
    }
  }

  // ---- load rows -----------------------------------------------------------
  async function loadRows(date: string, rid: string) {
    if (!date) return;
    setLoading(true);
    setError("");
    setRows([]);
    setExpandedRowId(null);
    setHoldingsRows([]);
    setIssuesByCell({});
    setPendingEdits({});
    setRecalcedCells({});

    try {
      const response = await api.getReviewRows("security_master", rid || undefined, date);
      const responseAny = response as unknown as Record<string, unknown>;
      const fetched = (response.rows ?? []) as ReviewRow[];
      setRows(fetched);
      setApprovalState(String(responseAny.approval_state ?? "pending_review"));

      // resolve runId from the response if we didn't have one
      const resolvedRunId = rid || String(responseAny.run_id ?? "");
      if (resolvedRunId && !rid) {
        setRunId(resolvedRunId);
      }

      if (resolvedRunId) {
        void fetchIssues(resolvedRunId);
        void fetchRunMeta(resolvedRunId);
      }
    } catch (err) {
      setError(String((err as Error).message ?? err));
    } finally {
      setLoading(false);
    }
  }

  async function fetchRunMeta(rid: string) {
    try {
      const status = await api.getPipelineExecutionStatus([rid]);
      const runs = (status.runs ?? []) as unknown as Array<Record<string, unknown>>;
      if (runs.length > 0) {
        setPipelineRuns(runs);
        setRunStartedAt(String(runs[0].started_at ?? ""));
        const runStatus = String(runs[0].status ?? "");
        if (runStatus === "exported") setApprovalState("exported");
        else if (runStatus === "pending_review") setApprovalState("pending_review");
        else if (runStatus === "approved") setApprovalState("approved");
      }
    } catch {
      // non-critical
    }
  }

  async function refreshRows() {
    if (!businessDate) return;
    try {
      const response = await api.getReviewRows("security_master", runId || undefined, businessDate);
      setRows((response.rows ?? []) as ReviewRow[]);
    } catch {
      // silent refresh — don't overwrite errors
    }
  }

  async function fetchIssues(rid: string) {
    try {
      const issues = await api.getReviewDataIssues("security_master", rid);
      const typed = issues as RowsetRow[];
      setIssueRows(typed.filter((r) => String(r.issue_status) === "open"));
      setIssuesByCell(buildIssueCellMap(typed));
    } catch {
      // issues are decorative — don't surface errors
    }
  }

  // ---- date change ---------------------------------------------------------
  async function handleDateChange(date: string) {
    setBusinessDate(date);
    setRunId("");
    setExpandedRowId(null);
    setHoldingsRows([]);

    // find matching snapshot
    const match = snapshotOptions.find((s) => String(s.business_date) === date);
    const rid = match ? String(match.run_id ?? "") : "";
    setRunId(rid);
    await loadRows(date, rid);
  }

  // ---- expand / collapse ---------------------------------------------------
  async function toggleExpand(rowId: number) {
    if (expandedRowId === rowId) {
      setExpandedRowId(null);
      setHoldingsRows([]);
      return;
    }

    setExpandedRowId(rowId);
    setHoldingsRows([]);
    setLoadingHoldings(true);

    try {
      const holdings = await api.getSecurityHoldings(rowId);
      const sorted = sortByFiler(holdings as RowsetRow[]);
      setHoldingsRows(sorted);
      if (editedSecurityRows.has(rowId)) {
        const touched: Record<string, true> = {};
        for (const h of sorted) {
          const hid = Number(h.holding_review_row_id ?? 0);
          touched[cellKey(hid, "holding_pct_of_outstanding")] = true;
        }
        setRecalcedCells((prev) => ({ ...prev, ...touched }));
      }
    } catch (err) {
      setError(String((err as Error).message ?? err));
    } finally {
      setLoadingHoldings(false);
    }
  }

  // ---- cell editing --------------------------------------------------------
  // pendingEdits = staged edits not yet sent to API (keyed by "rowId:column")
  // Each value is a JSON string: {value, table, inputColumn}

  const editOriginalRef = useRef<string>("");

  function startEdit(
    e: React.MouseEvent,
    rowId: number,
    column: string,
    table: string,
    currentValue: unknown,
  ) {
    e.stopPropagation();
    const formatted = formatValue(currentValue, column);
    editOriginalRef.current = formatted;
    setEditingCell({ rowId, column, table });
    setEditValue(formatted);
    setError("");
    setTimeout(() => editInputRef.current?.select(), 0);
  }

  function stageEdit(rowId: number, column: string, table: string, inputColumn?: string) {
    const value = editValue.trim();
    const original = editOriginalRef.current.trim();
    const key = cellKey(rowId, column);
    setEditingCell(null);
    if (value === original) return;
    setPendingEdits((prev) => ({
      ...prev,
      [key]: JSON.stringify({ value, table, inputColumn: inputColumn ?? column }),
    }));
  }

  function isValidNumeric(value: string): boolean {
    return /^-?\d*\.?\d+$/.test(value);
  }

  async function commitSingleEdit(rowId: number, column: string, table: string, inputColumn?: string) {
    const value = editValue.trim();
    const original = editOriginalRef.current.trim();
    setEditingCell(null);
    if (!value || value === original) return;
    if (!isValidNumeric(value)) {
      setError(`Invalid value "${value}" — must be a number`);
      return;
    }
    setCommitting(true);
    try {
      await commitOneCell(rowId, column, value, table, inputColumn ?? column);
    } catch (err) {
      setError(String((err as Error).message ?? err));
    } finally {
      setCommitting(false);
    }
  }

  async function commitAllStaged() {
    const entries = Object.entries(pendingEdits);
    if (entries.length === 0) return;
    const invalid = entries.filter(([, p]) => {
      const { value } = JSON.parse(p) as { value: string };
      return !isValidNumeric(value);
    });
    if (invalid.length > 0) {
      setError(`${invalid.length} staged edit(s) have invalid values — must be numbers`);
      return;
    }
    setCommitting(true);
    try {
      for (const [key, payload] of entries) {
        const [rowIdStr, column] = key.split(":");
        const { value, table, inputColumn } = JSON.parse(payload) as { value: string; table: string; inputColumn: string };
        await commitOneCell(Number(rowIdStr), column, value, table, inputColumn);
      }
      setPendingEdits({});
    } catch (err) {
      setError(String((err as Error).message ?? err));
    } finally {
      setCommitting(false);
    }
  }

  async function commitOneCell(rowId: number, column: string, value: string, table: string, inputColumn: string) {
    const secCalcCols = ["free_float_pct_raw", "investability_factor_raw", "free_float_shares", "investable_shares", "review_materiality_score"];
    const holdCalcCols = ["holding_pct_of_outstanding", "derived_price_per_share", "portfolio_weight", "market_value"];

    const beforeSecRows = new Map(rows.map((r) => [Number(r.review_row_id), r]));
    const beforeHoldRows = new Map(holdingsRows.map((h) => [Number(h.holding_review_row_id ?? 0), h]));

    await api.applyCellEdit({ review_table: table, row_id: rowId, column_name: inputColumn, new_value: value, changed_by: "ui" });

    if (table === "review.security_master_daily") {
      await api.recalcSecurity(rowId);
      setEditedSecurityRows((prev) => new Set(prev).add(rowId));
    } else {
      await api.recalcHolding(rowId);
    }

    const response = await api.getReviewRows("security_master", runId || undefined, businessDate);
    const newRows = (response.rows ?? []) as ReviewRow[];
    setRows(newRows);

    let newHoldings: RowsetRow[] = [];
    if (expandedRowId !== null) {
      const h = await api.getSecurityHoldings(expandedRowId);
      newHoldings = sortByFiler(h as RowsetRow[]);
      setHoldingsRows(newHoldings);
    }

    // Mark the edited cell as committed (green)
    const editedKey = cellKey(rowId, column);
    setPendingEdits((prev) => { const next = { ...prev }; delete next[editedKey]; return next; });
    setRecalcedCells((prev) => {
      const touched: Record<string, true> = { ...prev };
      // Mark the directly edited cell as green
      touched[editedKey] = true;
      // Diff security rows
      for (const afterRow of newRows) {
        const rid = Number(afterRow.review_row_id);
        const beforeRow = beforeSecRows.get(rid);
        if (!beforeRow) continue;
        for (const col of secCalcCols) {
          if (String(beforeRow[col] ?? "") !== String(afterRow[col] ?? "")) {
            touched[cellKey(rid, col)] = true;
          }
        }
      }
      // Diff holding rows
      for (const afterH of newHoldings) {
        const hid = Number(afterH.holding_review_row_id ?? 0);
        const beforeH = beforeHoldRows.get(hid);
        if (!beforeH) continue;
        for (const col of holdCalcCols) {
          if (String(beforeH[col] ?? "") !== String(afterH[col] ?? "")) {
            touched[cellKey(hid, col)] = true;
          }
        }
      }
      return touched;
    });

    if (runId) void fetchIssues(runId);
  }

  function handleEditKeyDown(
    e: KeyboardEvent<HTMLInputElement>,
    rowId: number,
    column: string,
    table: string,
    inputColumn?: string,
  ) {
    if (e.key === "Enter") {
      void commitSingleEdit(rowId, column, table, inputColumn);
    } else if (e.key === "Escape") {
      setEditingCell(null);
    }
  }

  function handleEditBlur(rowId: number, column: string, table: string, inputColumn?: string) {
    stageEdit(rowId, column, table, inputColumn);
  }

  // ---- approve & export ----------------------------------------------------
  async function handleApprove() {
    if (!businessDate || !runId) return;
    setApproving(true);
    setError("");
    try {
      await api.validateWorkspace({ business_date: businessDate, run_id: runId || undefined, actor: "ui" });
      setApprovalState("approved");
      setPipelineOpen(true);
      void pollExportCompletion();
    } catch (err) {
      setError(String((err as Error).message ?? err));
    } finally {
      setApproving(false);
    }
  }

  async function pollExportCompletion() {
    let attempts = 0;
    const poll = async () => {
      attempts++;
      try {
        // Check the pipeline run status directly
        const rid = runId;
        if (rid) {
          const status = await api.getPipelineExecutionStatus([rid]);
          const runs = (status.runs ?? []) as unknown as Array<Record<string, unknown>>;
          if (runs.length > 0) {
            setPipelineRuns(runs);
            const runStatus = String(runs[0].status ?? "");
            if (runStatus === "exported") {
              setApprovalState("exported");
              await reloadAfterPipeline();
              return;
            }
            if (["failed", "blocked"].includes(runStatus)) {
              setError("Export failed");
              return;
            }
          }
        }

        if (attempts > 60) {
          await reloadAfterPipeline();
          return;
        }

        setTimeout(() => void poll(), 3000);
      } catch {
        await reloadAfterPipeline();
      }
    };
    void poll();
  }

  // ---- reset ---------------------------------------------------------------
  async function handleReset() {
    if (!confirm("Reset the workbench? This will wipe all data and start fresh.")) return;
    setError("");
    try {
      await api.resetWorkbench();
      setRows([]);
      setExpandedRowId(null);
      setHoldingsRows([]);
      setIssuesByCell({});
      setIssueRows([]);
      setPendingEdits({});
      setRecalcedCells({});
      setApprovalState("pending_review");
      setRunId("");
      setSnapshotOptions([]);
      setPipelineRuns([]);
      void bootstrap();
    } catch (err) {
      setError(String((err as Error).message ?? err));
    }
  }

  // ---- get data (capture sources only) --------------------------------------
  async function handleGetData() {
    if (!businessDate) return;
    setCapturing(true);
    setCaptureComplete(false);
    setError("");
    try {
      await api.captureSources({ pipeline_code: "security_shareholder", dataset_code: "security_master", business_date: businessDate, actor: "ui" });
      const dates = await api.getAvailableSourceDates("security_master");
      const readyDates = new Set(dates.filter((d) => d.is_ready).map((d) => String(d.business_date)));
      const dateStrings = dates.map((d) => String(d.business_date ?? d)).sort();
      setAvailableDates(dateStrings);
      setAvailableDateSet(readyDates);
      setCaptureComplete(true);
    } catch (err) {
      setError(String((err as Error).message ?? err));
    } finally {
      setCapturing(false);
    }
  }

  // ---- delete source files ---------------------------------------------------
  async function handleDeleteSources() {
    if (!businessDate) return;
    if (!confirm(`Delete all source files for ${businessDate}? This cannot be undone.`)) return;
    setDeletingSources(true);
    setError("");
    try {
      await api.deleteSourceFiles({ pipeline_code: "security_shareholder", dataset_code: "security_master", business_date: businessDate, actor: "ui" });
      const dates = await api.getAvailableSourceDates("security_master");
      const readyDates = new Set(dates.filter((d) => d.is_ready).map((d) => String(d.business_date)));
      const dateStrings = dates.map((d) => String(d.business_date ?? d)).sort();
      setAvailableDates(dateStrings);
      setAvailableDateSet(readyDates);
      setCaptureComplete(false);
    } catch (err) {
      setError(String((err as Error).message ?? err));
    } finally {
      setDeletingSources(false);
    }
  }

  // ---- load pipeline --------------------------------------------------------
  async function handleLoadDate() {
    if (!businessDate) return;
    setLaunching(true);
    setError("");
    setPipelineOpen(true);
    try {
      const result = await api.launchPipelineForDate({ pipeline_code: "security_shareholder", dataset_code: "security_master", business_date: businessDate, actor: "ui" });
      const runIds = (result as unknown as Record<string, unknown>).run_ids as string[] | undefined;
      if (runIds && runIds.length > 0) {
        void pollExecution(runIds);
      }
    } catch (err) {
      setError(String((err as Error).message ?? err));
      setLaunching(false);
    }
  }

  async function pollExecution(runIds: string[]) {
    let attempts = 0;
    const poll = async () => {
      attempts++;
      try {
        const status = await api.getPipelineExecutionStatus(runIds);
        const runs = (status.runs ?? []) as unknown as Array<Record<string, unknown>>;
        setPipelineRuns(runs);

        const runStatus = runs.length > 0 ? String(runs[0].status ?? "") : "";
        if (runStatus === "exported") setApprovalState("exported");
        else if (runStatus === "pending_review") setApprovalState("pending_review");

        const isDone = status.is_complete
          || ["pending_review", "exported", "failed", "blocked"].includes(runStatus)
          || attempts > 90;

        if (!isDone) {
          setTimeout(() => void poll(), 2000);
        } else {
          setLaunching(false);
          await reloadAfterPipeline();
        }
      } catch {
        setLaunching(false);
        await reloadAfterPipeline();
      }
    };
    void poll();
  }

  async function reloadAfterPipeline() {
    try {
      const [dates, snapshots] = await Promise.all([
        api.getAvailableSourceDates("security_master"),
        api.getReviewSnapshots("security_master"),
      ]);
      setAvailableDates(dates.map((d) => String(d.business_date ?? d)).sort());
      setAvailableDateSet(new Set(dates.filter((d) => d.is_ready).map((d) => String(d.business_date))));
      setSnapshotOptions(snapshots as unknown as Array<Record<string, unknown>>);
      const match = snapshots.find((s) => s.business_date === businessDate);
      if (match) {
        const rid = String(match.run_id ?? "");
        setRunId(rid);
        await loadRows(businessDate, rid);
      }
    } catch {
      // fallback — try loading directly
      await loadRows(businessDate, "");
    }
  }

  // ---- render helpers ------------------------------------------------------
  const openIssueCount = issueRows.length;
  const pendingEditCount = Object.keys(pendingEdits).length;

  function cellClass(column: string, rowId?: number): string {
    if (rowId === undefined) return "";
    const key = cellKey(rowId, column);
    if (pendingEdits[key]) return "cell-state-pending";
    if (recalcedCells[key]) return "cell-state-calculated";
    return "";
  }

  function editableCellClass(column: string, rowId: number): string {
    const key = cellKey(rowId, column);
    if (pendingEdits[key]) return "cell-state-pending";
    if (recalcedCells[key]) return "cell-state-committed";
    return "";
  }

  function renderEditableCell(
    rowData: Record<string, unknown>,
    rowIdKey: string,
    displayColumn: string,
    table: string,
    inputColumn?: string,
  ) {
    const rowId = Number(rowData[rowIdKey] ?? 0);
    const key = cellKey(rowId, displayColumn);
    const isEditing = editingCell?.rowId === rowId && editingCell?.column === displayColumn;
    const hasIssue = Boolean(issuesByCell[key]);
    const isPending = Boolean(pendingEdits[key]);

    if (isEditing) {
      return (
        <input
          ref={editInputRef}
          className="inline-edit-input"
          value={editValue}
          onChange={(e) => {
            const next = e.target.value;
            setEditValue(next);
            const key = cellKey(rowId, displayColumn);
            if (next.trim() !== editOriginalRef.current.trim()) {
              setPendingEdits((prev) => ({
                ...prev,
                [key]: JSON.stringify({ value: next.trim(), table, inputColumn: inputColumn ?? displayColumn }),
              }));
            } else {
              setPendingEdits((prev) => { const n = { ...prev }; delete n[key]; return n; });
            }
          }}
          onKeyDown={(e) => handleEditKeyDown(e, rowId, displayColumn, table, inputColumn)}
          onBlur={() => handleEditBlur(rowId, displayColumn, table, inputColumn)}
          onClick={(e) => e.stopPropagation()}
          autoFocus
        />
      );
    }

    return (
      <span
        className={`editable-cell${hasIssue ? " cell-state-issue-target" : ""}${isPending ? " cell-state-committed" : ""}`}
        onClick={(e) => startEdit(e, rowId, displayColumn, table, rowData[displayColumn])}
        title="Click to edit"
      >
        {formatValue(rowData[displayColumn], displayColumn)}
        {hasIssue && <span className="issue-dot" title="Open issue" />}
      </span>
    );
  }

  // ---- render --------------------------------------------------------------
  const hasData = rows.length > 0;
  const dateIsReady = availableDateSet.has(businessDate);
  const dateHasSources = availableDates.includes(businessDate);

  return (
    <div className="review-workbench">
      {/* Top control area: two columns */}
      <div style={{ display: "flex", gap: "1.5rem", alignItems: "flex-start" }}>
        {/* Left: calendar + buttons + DAG */}
        <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
          <div style={{ display: "flex", gap: "1rem", alignItems: "flex-start" }}>
            <div className="inline-calendar">
              <div className="inline-calendar__header">
                <button type="button" onClick={() => setCalendarMonth((m) => addMonths(m, -1))}>&lsaquo;</button>
                <span>{monthLabel(calendarMonth)}</span>
                <button type="button" onClick={() => setCalendarMonth((m) => addMonths(m, 1))}>&rsaquo;</button>
              </div>
              <div className="inline-calendar__weekdays">
                {WEEKDAY_LABELS.map((d) => <span key={d}>{d}</span>)}
              </div>
              <div className="inline-calendar__days">
                {(() => {
                  const first = startOfMonth(calendarMonth);
                  const offset = mondayWeekdayIndex(first);
                  const daysInMonth = new Date(first.getFullYear(), first.getMonth() + 1, 0).getDate();
                  const today = toIsoDate(new Date());
                  const cells: React.ReactNode[] = [];
                  for (let i = 0; i < offset; i++) cells.push(<span key={`pad-${i}`} />);
                  for (let d = 1; d <= daysInMonth; d++) {
                    const iso = toIsoDate(new Date(first.getFullYear(), first.getMonth(), d));
                    const isAvailable = availableDateSet.has(iso);
                    const hasAnySources = availableDates.includes(iso);
                    const isSelected = iso === businessDate;
                    const isFuture = iso > today;
                    const isBusinessDay = businessDaySet.size === 0 || businessDaySet.has(iso);
                    const isNonBusinessDay = !isBusinessDay && !isFuture;
                    const isDisabled = isFuture || (isNonBusinessDay && !hasAnySources);
                    const holiday = holidayMap[iso];
                    const cls = isSelected ? "cal-day selected"
                      : isAvailable ? "cal-day available"
                      : hasAnySources ? "cal-day available"
                      : isFuture || isNonBusinessDay ? "cal-day future"
                      : "cal-day inactive";
                    cells.push(
                      <button key={iso} type="button" className={cls}
                        disabled={isDisabled}
                        title={holiday || (isNonBusinessDay && !hasAnySources ? "Non-business day" : "")}
                        onClick={() => void handleDateChange(iso)}>{d}</button>
                    );
                  }
                  return cells;
                })()}
              </div>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "0.4rem" }}>
              <div className="review-toolbar">
                <button className="primary-button" disabled={!businessDate || dateIsReady || capturing}
                  onClick={() => void handleGetData()}>{capturing ? "Fetching\u2026" : "Get Data"}</button>
                <button className="approve-button" disabled={!dateIsReady || launching || hasData}
                  onClick={() => void handleLoadDate()}>{launching ? "Loading\u2026" : "Load Data"}</button>
                <button className="danger-button" disabled={!dateHasSources || hasData || deletingSources}
                  onClick={() => void handleDeleteSources()}>{deletingSources ? "Deleting\u2026" : "Delete Source Files"}</button>
              </div>
              <PipelineDag
                steps={pipelineRuns.length > 0 ? ((pipelineRuns[0].steps ?? []) as Array<Record<string, unknown>>) : []}
                pipelineStatus={pipelineRuns.length > 0 ? String(pipelineRuns[0].status ?? "") : (hasData ? "pending_review" : "")}
                capturing={capturing}
                captureComplete={captureComplete}
                sourcesReady={dateIsReady}
                approvalState={approvalState}
              />
            </div>
          </div>
        </div>

        {/* Right: metadata panel */}
        {(runId || hasData) && (
          <div className="run-metadata-panel" style={{ minWidth: "200px" }}>
            <dl className="run-metadata-grid">
              <dt>Run ID</dt><dd title={runId}>{runId}</dd>
              <dt>Business Date</dt><dd>{businessDate}</dd>
              <dt>Status</dt>
              <dd>
                <span className={`status-dot ${approvalState === "approved" || approvalState === "exported" ? "ok" : approvalState === "pending_review" ? "pending" : ""}`} />
                {approvalState.replace(/_/g, " ")}
              </dd>
              <dt>Securities</dt><dd>{hasData ? rows.length : "\u2014"}</dd>
              {runStartedAt ? (
                <React.Fragment><dt>Pipeline Run</dt><dd>{new Date(runStartedAt).toLocaleString()}</dd></React.Fragment>
              ) : null}
            </dl>
          </div>
        )}
      </div>

      {/* Issues panel — collapsible */}
      {issueRows.length > 0 && (
        <div style={{ border: "1px solid var(--border-subtle)", borderRadius: "0.35rem", overflow: "hidden", width: "fit-content" }}>
          <button
            onClick={() => setIssuesPanelOpen((v) => !v)}
            style={{ width: "100%", background: "var(--bg-panel-elevated)", border: "none", padding: "0.4rem 0.75rem", cursor: "pointer", textAlign: "left", display: "flex", alignItems: "center", gap: "0.5rem", fontSize: "0.82rem" }}
          >
            <span style={{ color: "var(--accent-red)", fontWeight: 600 }}>{openIssueCount}</span>
            <span style={{ color: "var(--text-secondary)" }}>data quality {openIssueCount === 1 ? "issue" : "issues"}</span>
            <span style={{ color: "var(--text-dim)", marginLeft: "auto", fontSize: "0.75rem" }}>{issuesPanelOpen ? "\u25b4" : "\u25be"}</span>
          </button>
          {issuesPanelOpen && (
            <div style={{ maxHeight: "180px", overflow: "auto", borderTop: "1px solid var(--border-subtle)" }}>
              <table className="data-table" style={{ fontSize: "0.8rem", width: "auto" }}>
                <thead>
                  <tr>
                    <th style={{ color: "var(--accent-red)", fontSize: "0.7rem", textTransform: "uppercase", whiteSpace: "nowrap" }}>Category</th>
                    <th style={{ fontSize: "0.7rem", textTransform: "uppercase", whiteSpace: "nowrap" }}>Ticker</th>
                    <th style={{ fontSize: "0.7rem", textTransform: "uppercase", whiteSpace: "nowrap" }}>Issue</th>
                    <th style={{ fontSize: "0.7rem", textTransform: "uppercase", whiteSpace: "nowrap" }}>Column</th>
                  </tr>
                </thead>
                <tbody>
                  {issueRows.map((issue, i) => {
                    const issueRowId = Number(issue.review_row_id ?? 0);
                    const matchedSec = rows.find((r) => Number(r.review_row_id) === issueRowId);
                    return (
                      <tr key={`issue-${i}`} style={{ cursor: "pointer" }}
                        onClick={() => {
                          void toggleExpand(issueRowId);
                          setTimeout(() => {
                            const el = tableWrapRef.current?.querySelector(`[data-row-id="${issueRowId}"]`);
                            if (el) el.scrollIntoView({ behavior: "smooth", block: "center" });
                          }, 100);
                        }}>
                        <td style={{ color: "var(--accent-red)", whiteSpace: "nowrap" }}>{String(issue.issue_category ?? "")}</td>
                        <td style={{ fontFamily: "monospace", fontWeight: 600, whiteSpace: "nowrap" }}>{matchedSec ? String(matchedSec.ticker ?? "") : String(issue.review_row_id ?? "")}</td>
                        <td style={{ whiteSpace: "nowrap" }}>{String(issue.issue_message ?? issue.issue_code ?? "")}</td>
                        <td style={{ fontFamily: "monospace", color: "var(--text-muted)", whiteSpace: "nowrap" }}>{Array.isArray(issue.offending_columns) ? (issue.offending_columns as string[]).join(", ") : String(issue.offending_columns ?? "")}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* Action buttons */}
      {hasData && (
        <div className="review-toolbar">
          <button
            className="primary-button"
            disabled={pendingEditCount === 0 || committing}
            onClick={() => void commitAllStaged()}
          >
            {committing ? "Committing\u2026" : `Commit${pendingEditCount > 0 ? ` (${pendingEditCount})` : ""}`}
          </button>

          <button
            className="warning-button"
            disabled={pendingEditCount === 0 || committing}
            onClick={() => setPendingEdits({})}
          >
            Discard
          </button>

          <button
            className="approve-button"
            disabled={approving || !businessDate || rows.length === 0 || approvalState === "approved" || approvalState === "exported"}
            onClick={() => void handleApprove()}
          >
            {approvalState === "exported" ? "Exported" : approvalState === "approved" ? "Approved" : approving ? "Approving\u2026" : "Approve & Export"}
          </button>

          <button
            className="danger-button"
            disabled={approving || committing}
            onClick={() => void handleReset()}
          >
            Reset
          </button>
        </div>
      )}

      {/* Error banner */}
      {error && (
        <div className="error-banner">
          {error}
          <button className="error-banner-close" onClick={() => setError("")}>&times;</button>
        </div>
      )}

      {/* Empty / loading — centered */}
      {!hasData && (loading || businessDate) && (
        <div style={{ display: "flex", justifyContent: "center", alignItems: "center", minHeight: "calc(100vh - 22rem)" }}>
          <span style={{ color: "var(--text-muted)", fontSize: "0.95rem" }}>
            {loading ? "Loading\u2026" : businessDate ? `No data for ${businessDate}` : ""}
          </span>
        </div>
      )}

      {/* Main table */}
      {hasData && (
      <div
        ref={tableWrapRef}
        className="table-wrap review-table-wrap"
        style={{ maxHeight: "calc(100vh - 10rem)", overflow: "auto", maxWidth: "fit-content" }}
      >
          <table className="data-table review-data-table">
            <thead>
              <tr>
                <th style={{ width: "1.5rem" }}></th>
                <th>Ticker</th>
                <th>Issuer</th>
                <th>Exchange</th>
                <th className="column-state-editable">Shares Outstanding</th>
                <th className="column-state-calculated">Free Float %</th>
                <th className="column-state-calculated">Investability</th>
                <th className="column-state-calculated">Free Float Shares</th>
                <th className="column-state-calculated">Investable Shares</th>
                <th className="column-state-calculated">Materiality</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => {
                const rowId = Number(row.review_row_id ?? 0);
                const isExpanded = expandedRowId === rowId;
                const ticker = String(row.ticker ?? "");

                return (
                  <React.Fragment key={rowId}>
                    <tr
                      data-row-id={rowId}
                      className={`security-row${isExpanded ? " expanded" : ""}`}
                      onClick={() => void toggleExpand(rowId)}
                      style={{ cursor: "pointer" }}
                    >
                      <td className="expand-cell">{isExpanded ? "\u25be" : "\u25b8"}</td>
                      <td style={{ fontWeight: 600, fontFamily: "monospace" }}>{ticker}</td>
                      <td>{String(row.issuer_name ?? "")}</td>
                      <td style={{ color: "var(--text-secondary)" }}>{String(row.exchange ?? "")}</td>
                      <td className={editableCellClass("shares_outstanding_raw", rowId)} onClick={(e) => e.stopPropagation()}>{renderEditableCell(row as Record<string, unknown>, "review_row_id", "shares_outstanding_raw", "review.security_master_daily")}</td>
                      <td className={cellClass("free_float_pct_raw", rowId)}>{formatValue(row.free_float_pct_raw, "free_float_pct_raw")}</td>
                      <td className={cellClass("investability_factor_raw", rowId)}>{formatValue(row.investability_factor_raw, "investability_factor_raw")}</td>
                      <td className={cellClass("free_float_shares", rowId)}>{formatValue(row.free_float_shares, "free_float_shares")}</td>
                      <td className={cellClass("investable_shares", rowId)}>{formatValue(row.investable_shares, "investable_shares")}</td>
                      <td className={cellClass("review_materiality_score", rowId)}>{formatValue(row.review_materiality_score, "review_materiality_score")}</td>
                    </tr>

                    {isExpanded && (
                      <tr key={`${rowId}-holdings`}>
                        <td colSpan={10} style={{ padding: 0 }}>
                          <div className="holdings-scroll-container">
                            <div className="holdings-title-bar">
                              {loadingHoldings
                                ? `Loading holdings for ${ticker}\u2026`
                                : `Holdings for ${ticker} (${holdingsRows.length} filers)`}
                            </div>
                            {!loadingHoldings && holdingsRows.length > 0 && (
                              <table className="data-table holdings-subtable">
                                <thead>
                                  <tr>
                                    <th style={dimUpperStyle}>Filer</th>
                                    <th style={{...dimUpperStyle, color: "var(--accent-blue)"}}>Shares Held</th>
                                    <th style={{...dimUpperStyle, color: "var(--accent-purple)"}}>% of Outstanding</th>
                                    <th style={{...dimUpperStyle, color: "var(--accent-purple)"}}>Implied Price</th>
                                    <th style={{...dimUpperStyle, color: "var(--accent-blue)"}}>Market Value</th>
                                    <th style={{...dimUpperStyle, color: "var(--accent-purple)"}}>Portfolio Wt.</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  {holdingsRows.map((h) => {
                                    const hId = Number(h.holding_review_row_id ?? 0);
                                    return (
                                      <tr key={hId || String(h.filer_name)} className="holdings-row">
                                        <td>{String(h.filer_name ?? "")}</td>
                                        <td className={editableCellClass("shares_held", hId)} onClick={(e) => e.stopPropagation()}>{renderEditableCell(h as Record<string, unknown>, "holding_review_row_id", "shares_held", "review.shareholder_holdings_daily", "shares_held_raw")}</td>
                                        <td className={recalcedCells[cellKey(hId, "holding_pct_of_outstanding")] ? "cell-state-calculated" : ""}>{formatValue(h.holding_pct_of_outstanding, "holding_pct_of_outstanding")}</td>
                                        <td className={recalcedCells[cellKey(hId, "derived_price_per_share")] ? "cell-state-calculated" : ""}>{formatValue(h.derived_price_per_share, "derived_price_per_share")}</td>
                                        <td className={editableCellClass("market_value", hId)} onClick={(e) => e.stopPropagation()}>{renderEditableCell(h as Record<string, unknown>, "holding_review_row_id", "market_value", "review.shareholder_holdings_daily", "reviewed_market_value_raw")}</td>
                                        <td className={recalcedCells[cellKey(hId, "portfolio_weight")] ? "cell-state-calculated" : ""}>{formatValue(h.portfolio_weight, "portfolio_weight")}</td>
                                      </tr>
                                    );
                                  })}
                                </tbody>
                              </table>
                            )}
                          </div>
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                );
              })}
            </tbody>
          </table>
      </div>
      )}
    </div>
  );
}
