#!/usr/bin/env python3
"""Regenerate static platform files from config.json.

Run after adding or removing a workflow:
    make sync-config

Currently generates:
    dbt/dbt_project.yml          — model-paths, test-paths, and models config block
    apps/dagster/workspace.yaml  — one gRPC code location per workflow
    docker-compose.override.yml  — one dagster-user-code service per workflow
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = REPO_ROOT / "config.json"
DBT_PROJECT_PATH = REPO_ROOT / "dbt" / "dbt_project.yml"
WORKSPACE_PATH = REPO_ROOT / "apps" / "dagster" / "workspace.yaml"
COMPOSE_OVERRIDE_PATH = REPO_ROOT / "docker-compose.override.yml"

LAYER_SCHEMAS = [
    ("staging", "staging"),
    ("intermediate", "intermediate"),
    ("marts", "marts"),
    ("exports", "export"),
]


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def _models_block(workflows: list[dict]) -> str:
    lines = ["models:", "  dagflow:", "    +materialized: table"]
    for wf in workflows:
        lines.append(f"    {wf['name']}:")
        for layer, schema in LAYER_SCHEMAS:
            lines.append(f"      {layer}:")
            lines.append(f"        +schema: {schema}")
    return "\n".join(lines)


def _list_block(label: str, items: list[str]) -> str:
    lines = [f"{label}:"]
    for item in items:
        lines.append(f'  - "{item}"')
    return "\n".join(lines)


def generate_dbt_project(workflows: list[dict]) -> str:
    model_paths = [f"../{wf['path']}/dbt/models" for wf in workflows]
    test_paths = [f"../{wf['path']}/dbt/tests" for wf in workflows]
    jinja_hook = "{{ log_dq_results(results) }}"

    sections = [
        "# Generated by ops/scripts/sync_config.py — do not edit manually.",
        "# Edit config.json at the repo root, then run: make sync-config",
        "",
        "name: dagflow",
        "version: 1.0.0",
        "config-version: 2",
        "",
        "profile: dagflow",
        "",
        _list_block("model-paths", model_paths),
        _list_block("snapshot-paths", ["snapshots"]),
        _list_block("test-paths", test_paths),
        _list_block("macro-paths", ["macros"]),
        "",
        "target-path: target",
        "clean-targets:",
        "  - target",
        "  - dbt_packages",
        "  - logs",
        "",
        _models_block(workflows),
        "",
        "snapshots:",
        "  dagflow:",
        "    +target_schema: marts",
        "",
        "on-run-end:",
        f'  - "{jinja_hook}"',
        "",
    ]
    return "\n".join(sections)


def generate_workspace(workflows: list[dict]) -> str:
    lines = [
        "# Generated by ops/scripts/sync_config.py — do not edit manually.",
        "# Edit config.json at the repo root, then run: make sync-config",
        "",
        "load_from:",
    ]
    for wf in workflows:
        host = f"dagster-user-code-{wf['name'].replace('_', '-')}"
        lines += [
            f"  - grpc_server:",
            f"      host: {host}",
            f"      port: 4000",
            f"      location_name: {wf['name']}",
        ]
    lines.append("")
    return "\n".join(lines)


def _e(var: str, default: str = "") -> str:
    """Format a docker-compose env var with optional default."""
    return f"${{{var}:-{default}}}" if default else f"${{{var}}}"


def generate_compose_override(workflows: list[dict]) -> str:
    lines = [
        "# Generated by ops/scripts/sync_config.py — do not edit manually.",
        "# Edit config.json at the repo root, then run: make sync-config",
        "",
        "services:",
    ]
    for wf in workflows:
        svc = f"dagster-user-code-{wf['name'].replace('_', '-')}"
        landing = f"/workspace/{wf['path']}/source_landing"
        export = f"/workspace/{wf['path']}/generated_exports"
        lines += [
            f"  {svc}:",
            f"    build:",
            f"      context: .",
            f"      dockerfile: apps/dagster/Dockerfile",
            f"    command: >",
            f"      dagster api grpc",
            f"      -h 0.0.0.0",
            f"      -p 4000",
            f"      -m {wf['package']}.definitions",
            f"    environment:",
            f"      APP_ENV: {_e('APP_ENV', 'local')}",
            f"      DATABASE_URL: {_e('DATABASE_URL', 'postgresql://postgres:postgres@pgbouncer:6432/dagflow')}",
            f"      DIRECT_DATABASE_URL: {_e('DIRECT_DATABASE_URL', 'postgresql://postgres:postgres@postgres:5432/dagflow')}",
            f"      DAGSTER_HOME: /opt/dagster/dagster_home",
            f"      DBT_PROFILES_DIR: /workspace/dbt",
            f"      LANDING_ROOT_DIR: {landing}",
            f"      EXPORT_ROOT_DIR: {export}",
            f"      EDGAR_IDENTITY: {_e('EDGAR_IDENTITY', 'Dagflow local dev support@dagflow.local')}",
            f"      SEC_13F_LOOKBACK_DAYS: {_e('SEC_13F_LOOKBACK_DAYS', '14')}",
            f"      SEC_13F_FILING_LIMIT: {_e('SEC_13F_FILING_LIMIT', '50')}",
            f"      SEC_SECURITY_FOCUS_LIMIT: {_e('SEC_SECURITY_FOCUS_LIMIT', '80')}",
            f"      OPENFIGI_API_KEY: {_e('OPENFIGI_API_KEY')}",
            f"      FINNHUB_API_KEY: {_e('FINNHUB_API_KEY')}",
            f"      MINIO_ENDPOINT: {_e('MINIO_ENDPOINT', 'minio:9000')}",
            f"      MINIO_ACCESS_KEY: {_e('MINIO_ACCESS_KEY', 'minio')}",
            f"      MINIO_SECRET_KEY: {_e('MINIO_SECRET_KEY', 'minio123')}",
            f"      MINIO_SECURE: {_e('MINIO_SECURE', 'false')}",
            f"    depends_on:",
            f"      postgres:",
            f"        condition: service_healthy",
            f"      pgbouncer:",
            f"        condition: service_started",
            f"      minio:",
            f"        condition: service_started",
            f"    volumes:",
            f"      - .:/workspace",
            f"      - dagster-home:/opt/dagster/dagster_home",
        ]
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    config = json.loads(CONFIG_PATH.read_text())
    workflows = config["workflows"]

    dbt_yml = generate_dbt_project(workflows)
    DBT_PROJECT_PATH.write_text(dbt_yml)
    print(f"  wrote {DBT_PROJECT_PATH.relative_to(REPO_ROOT)}")

    workspace_yml = generate_workspace(workflows)
    WORKSPACE_PATH.write_text(workspace_yml)
    print(f"  wrote {WORKSPACE_PATH.relative_to(REPO_ROOT)}")

    compose_override = generate_compose_override(workflows)
    COMPOSE_OVERRIDE_PATH.write_text(compose_override)
    print(f"  wrote {COMPOSE_OVERRIDE_PATH.relative_to(REPO_ROOT)}")

    print(f"sync-config complete — {len(workflows)} workflow(s) registered.")


if __name__ == "__main__":
    main()
