version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: sec_company_tickers
        meta:
          dagster:
            asset_key: ["security_shareholder__raw_tickers"]
      - name: sec_company_facts
        meta:
          dagster:
            asset_key: ["security_shareholder__raw_facts"]
      - name: holdings_13f
        meta:
          dagster:
            asset_key: ["security_shareholder__raw_holdings"]
      - name: holdings_13f_filers
        meta:
          dagster:
            asset_key: ["security_shareholder__raw_filers"]

  - name: review
    schema: review
    tables:
      - name: security_master_daily
        meta:
          dagster:
            asset_key: ["security_shareholder__review_securities"]
      - name: shareholder_holdings_daily
        meta:
          dagster:
            asset_key: ["security_shareholder__review_holdings"]
